(part "6318977-3"
    (packageRef "63189773")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "7" (symbPinId 6) (portName "7") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "6318977-3")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Board-to-Board, 6 Position, 2.5 mm [.098 in] Centerline, Plug, 30 VDC, Right Angle, Printed Circuit Board, Power & Signal, DC Jack Connectors")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=6318977&DocType=Customer%20Drawing&DocLang=English&PartCntxt=6318977-3&DocFormat=pdf")
    (property "symbolName1" "6318977-3")
)
