(part "5787526-1"
    (packageRef "57875261")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "5787526-1")
    (property "Mouser_Part_Number" "571-5787526-1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity/5787526-1?qs=Y377PMEofyCxYvQc9q%2F8iQ%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Body Features: Primary Product Color Black | Configuration Features: Number of Positions 6 | Contact Features: Contact Base Material Phosphor Bronze | Contact Current Rating (Max) 4 AMP | PCB Contact Termination Area Plating Material Tin | Contact Mating Area Plating Material Gold | Contact Underplating Material Nickel | Housing Features: Centerline (Pitch) .08 INCH | Centerline (Pitch) 2 MM | Industry Standards: UL Flammability Rating UL 94V-0 | Mechanical Attachment: PCB Mount Retention Type Hold-Down Pos")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=4-1773458-1_2_PIECE_POWER_CONNECTORS_QRG&DocType=Data%20Sheet&DocLang=English&PartCntxt=5787526-1&DocFormat=pdf")
    (property "symbolName1" "5787526-1")
)
