(part "1612901-1"
    (packageRef "16129011")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "9" (symbPinId 9) (portName "9") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "1612901-1")
    (property "Mouser_Part_Number" "571-1612901-1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity/1612901-1?qs=y6UIinpTn8jJ98k65QdKmA%3D%3D")
    (property "Arrow_Part_Number" "1612901-1")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/1612901-1/te-connectivity")
    (property "Description" "Cylindrical Battery Contacts, Clips, Holders & Springs BATTERY BLOCK CONN. REC ASSY 3")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Customer+Drawing%7F1612901%7FB%7Fpdf%7FEnglish%7FENG_CD_1612901_B.pdf%7F1612901-1")
    (property "symbolName1" "1612901-1")
)
