M48
; DRILL file {KiCad 9.0.6} date 2025-11-21T10:37:18+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-21T10:37:18+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.750
%
G90
G05
T1
X145.45Y-39.5
X152.85Y-39.5
X158.65Y-39.5
X166.05Y-39.5
T2
X155.75Y-150.75
T3
X146.89Y-133.1
X146.9Y-75.1
M30
