(part "1827654-1"
    (packageRef "18276541")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "MH1" (symbPinId 8) (portName "MH1") (portType INOUT))
        (port "MH2" (symbPinId 9) (portName "MH2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "1827654-1")
    (property "Mouser_Part_Number" "571-1827654-1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity/1827654-1?qs=y6UIinpTn8hD7CbWsVjTIg%3D%3D")
    (property "Arrow_Part_Number" "1827654-1")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/1827654-1/te-connectivity?utm_currency=USD&region=europe")
    (property "Description" "DC Jack Connectors, Board-to-Board, 7 Position, .079 in [2 mm] Centerline, Plug, 30 VDC, Right Angle, Printed Circuit Board, Power & Signal")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Customer+Drawing%7F1827654%7FD3%7Fpdf%7FEnglish%7FENG_CD_1827654_D3_c-1827654_drw.pdf%7F1827654-1")
    (property "symbolName1" "1827654-1")
)
